### ISSUE TITLE
[gotosocial] Allow hostname, username, and port as keys in existing SMTP Secret

### ISSUE THREAD

**Issue by jessebot** [0hlov3/charts#13]
### Is your feature request related to a problem ?

I would like to have all SMTP related data in an existing Secret. This lets me opensource my configuration without revealing my SMTP hostname, which could help with reconnaissance from bad actors.

### Describe the solution you'd like.

I'd like to see SMTP hostname, password, and port also allowed to be sourced from an existing secret. Here's what the values.yaml could look like for the smtp section:

```yaml
gotosocial:
  config:
    smtp:
      existingSecretName: ""
      existingSecretKeys:
        user: ""
        password: ""
        host: ""
        port: ""
```

### Describe alternatives you've considered.

NONE
