### ISSUE TITLE
[gotosocial] non fuctional sqlite in default setup

### ISSUE THREAD

**Issue by l-ra** [0hlov3/charts#4]
### Describe the bug a clear and concise description of what the bug is.

After almost default chart install with both local and external postgres disabled the server does not start with following error:

```
timestamp="06/08/2023 07:53:39.871" func=cache.(*Caches).Init level=INFO msg="init: 0xc00090e000"
timestamp="06/08/2023 07:53:39.871" func=cache.(*Caches).Start level=INFO msg="start: 0xc00090e000"
timestamp="06/08/2023 07:53:39.872" func=bundb.sqliteConn level=INFO msg="connected to SQLITE database with address file:/gotosocial/storage/sqlite.db?_txlock=immediate"
timestamp="06/08/2023 07:53:39.935" func=bundb.sqlitePragmas level=INFO msg="sqlite pragma journal_mode set to wal"
timestamp="06/08/2023 07:53:39.935" func=bundb.sqlitePragmas level=INFO msg="sqlite pragma synchronous set to 1"
timestamp="06/08/2023 07:53:39.935" func=bundb.sqlitePragmas level=INFO msg="sqlite pragma cache_size set to -8192"
timestamp="06/08/2023 07:53:39.935" func=bundb.sqlitePragmas level=INFO msg="sqlite pragma busy_timeout set to 1800000"
timestamp="06/08/2023 07:53:39.939" func=bundb.doMigration level=INFO msg="there are no new migrations to run"
2023/08/06 07:53:40 error executing command: error creating instance account: disk I/O error (6410)
timestamp="06/08/2023 07:53:40.247" func=cache.(*Caches).Stop level=INFO msg="stop: 0xc00090e000"
```

### What's your helm version?

3.8.2

### What's your kubectl version?

1.23.5

### Which chart?

gotosocial

### What's the chart version?

0.4.8

### What happened?

After almost default chart install with both local and external postgres disabled the server does not start with following error:

```
timestamp="06/08/2023 07:53:39.871" func=cache.(*Caches).Init level=INFO msg="init: 0xc00090e000"
timestamp="06/08/2023 07:53:39.871" func=cache.(*Caches).Start level=INFO msg="start: 0xc00090e000"
timestamp="06/08/2023 07:53:39.872" func=bundb.sqliteConn level=INFO msg="connected to SQLITE database with address file:/gotosocial/storage/sqlite.db?_txlock=immediate"
timestamp="06/08/2023 07:53:39.935" func=bundb.sqlitePragmas level=INFO msg="sqlite pragma journal_mode set to wal"
timestamp="06/08/2023 07:53:39.935" func=bundb.sqlitePragmas level=INFO msg="sqlite pragma synchronous set to 1"
timestamp="06/08/2023 07:53:39.935" func=bundb.sqlitePragmas level=INFO msg="sqlite pragma cache_size set to -8192"
timestamp="06/08/2023 07:53:39.935" func=bundb.sqlitePragmas level=INFO msg="sqlite pragma busy_timeout set to 1800000"
timestamp="06/08/2023 07:53:39.939" func=bundb.doMigration level=INFO msg="there are no new migrations to run"
2023/08/06 07:53:40 error executing command: error creating instance account: disk I/O error (6410)
timestamp="06/08/2023 07:53:40.247" func=cache.(*Caches).Stop level=INFO msg="stop: 0xc00090e000"
```

### What you expected to happen?

Server starts normally 

### How to reproduce it?

Install chart with default config with sqlite database option (both postgres disables)

### Enter the changed values of values.yaml?

```yaml
# subchart 
gotosocial:

  image:
    repository: superseriousbusiness/gotosocial
    pullPolicy: IfNotPresent

  replicaCount: 1

  ingress:
    enabled: true
    className: "nginx"
    annotations: 
      cert-manager.io/cluster-issuer: letsencrypt-issuer
      nginx.ingress.kubernetes.io/proxy-body-size: 10000m
      nginx.org/client-max-body-size: 10000m 
    hosts:
      - host: REDACTED
        paths:
          - path: /
            pathType: ImplementationSpecific
    tls: 
    - secretName: REDACTED-tls
      hosts:
      - REDACTED

  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 500m
      memory: 512Mi

  gotosocial:
    strategy:
      type: Recreate
    persistence:
      enabled: true
      accessMode: "ReadWriteOnce"
      size: "10Gi"
      #storageClass: ""
    config:
      #logLevel: "info"
      #logDBQueries: ""
      applicationName: "gotosocial"
      host: "REDACTED"
      accountDomain: "REDACTED"
      trustedProxies:
        - "10.0.0.0/8"
        - "172.16.0.0/12"
        - "192.168.0.0/16"
      web:
        templateBaseDir: "./web/template/" 
        assetBaseDir: "./web/assets/"

  postgresql:
    enabled: false

  externalPostgresql:
    enabled: false
    database: GoToSocial

  serviceAccount:
    create: true
    annotations: {}
    name: ""

  podAnnotations: {}

  podSecurityContext:
    runAsUser: 1000
    runAsGroup: 1000
    fsGroup: 1000

  securityContext:
    capabilities:
      drop: 
        - ALL
    readOnlyRootFilesystem: true
    allowPrivilegeEscalation: false
    runAsNonRoot: true
    runAsUser: 1000
    runAsGroup: 1000

  nodeSelector: {}

  tolerations: []

  affinity: {}
```

### Enter the command that you execute and failing/misfunctioning.

in context of chart which has goosocial as dependency

```
helm -n REDACETD install default . -f values.yaml 
```

### Anything else we need to know?

According to sqlite doc the error 6410 is a problem with temp file creation  as described here https://www.sqlite.org/rescode.html#ioerr_gettemppath

Can be fixed with [SQLITE_TMPDIR](https://www.sqlite.org/tempfiles.html#temporary_file_storage_locations) targeted to the same folder which is used for `sqlite.db` file

I'll try to send pull request
