### ISSUE TITLE
[gotosocial] Add support for arbitary initContainers

### ISSUE THREAD

**Issue by AmandaCameron** [0hlov3/charts#7]
### Is your feature request related to a problem ?

I'd like to be able to configure some networking stuff in my gotosocial container via an initContainer before the main container starts.

### Describe the solution you'd like.

I'd like an additional value/set of values in the values.yaml that gets translated into the gotosocial deployment's initContainers field

### Describe alternatives you've considered.

Forking the chart seems to be the only alternative for what I want to do with this, as network policies don't support blocking cidrs.

**Comment by 0hlov3** [comment]
@AmandaCameron, added the possibility, can you recheck if this matches the requirements?

```yaml
initContainers:
  - name: init-myservice
    image: busybox:1.28
    command: ['sh', '-c', "until nslookup myservice.$(cat /var/run/secrets
```
